# Target platform configuration
target: 
  platform: "SDXL"

# Detector configuration
detector:
  person:
    confidence_threshold: 0.5
    iou_threshold: 0.45
  face:
    confidence_threshold: 0.6
    iou_threshold: 0.35

# Tagger configuration
tagger:
  wd14:
    confidence: 0.35
    blacklist: []
  caption:
    max_length: 100
    temperature: 1.0
    repetition_penalty: 1.5
  orientation:
    confidence: 0.8
  nima:
    # We could add config overrides here, but the defaults in NIMA_tagger.py will work fine
    # technical_threshold: 0.5
    # aesthetic_threshold: 5.0
    # use_technical: true
    # use_aesthetic: true


# Device configuration
device:
  preferred: "mps"  # For Mac users
  fallback: "cpu"   # Always good to have a fallback

# Detection-tagger mapping
person:
  - wd14
  - caption
  - nima


face:
  - wd14
  - caption 
  - nima

processing:
  max_concurrent_batches: 1  # Number of batches to process simultaneously
  max_concurrent_images: 1   # Number of images to process simultaneously within each batch
  save_rejects: false     # Whether to save rejected images
